### ISSUE TITLE
TRUNCATE 在myBatis中怎么使用?

### ISSUE THREAD

**Issue by smchild** [makersoft/mybatis-shards#12]
在删除数据的时候老大建议用TRUNCATE ,之前在myBatis 中没有使用过，求救....

**Comment by smchild** [comment]
来晚了,多谢。

**Comment by hmilywq** [comment]
请问可以在mybatis里的mapper中配置truncate来批量删除数据吗？

**Comment by fengkuok** [comment]
@hmilywq 可以啊，没问题的

**Comment by hmilywq** [comment]
可以教我怎么用吗？谢了

发自我的 iPhone

**Comment by fengkuok** [comment]
直接在MyBatis Mapper文件的delete块写SQL语句执行即可。
郭峰    Feng Kuok

Email：guofengcn@126.com <mailto:zhouxiang@founder.com> Website：www.makersoft.org <http://www.founder.com.cn/>

**Comment by hmilywq** [comment]
可以帮我写一下吗？谢谢你了

发自我的 iPhone

> 在 2015/07/29，21:31，Feng Kuok <notifications@github.com> 写道：
> 
> 直接在MyBatis Mapper文件的delete块写SQL语句执行即可。
> 郭峰 Feng Kuok
> 
> Email：guofengcn@126.com <mailto:zhouxiang@founder.com> Website：www.makersoft.org <http://www.founder.com.cn/>

**Comment by hmilywq** [comment]
你说的是这么写吗？
〈delete〉
     truncate table 职员表
〈/delete〉

发自我的 iPhone

> 在 2015/07/29，21:31，Feng Kuok <notifications@github.com> 写道：
> 
> 直接在MyBatis Mapper文件的delete块写SQL语句执行即可。
> 郭峰 Feng Kuok
> 
> Email：guofengcn@126.com <mailto:zhouxiang@founder.com> Website：www.makersoft.org <http://www.founder.com.cn/>

**Comment by hmilywq** [comment]
兄弟，麻烦帮我一下呗。帮我写一下呗，谢谢你了

发自我的 iPhone

> 在 2015/07/29，21:31，Feng Kuok <notifications@github.com> 写道：
> 
> 直接在MyBatis Mapper文件的delete块写SQL语句执行即可。
> 郭峰 Feng Kuok
> 
> Email：guofengcn@126.com <mailto:zhouxiang@founder.com> Website：www.makersoft.org <http://www.founder.com.cn/>

**Comment by hmilywq** [comment]
是这么写吗？

发自我的 iPhone
