### ISSUE TITLE
请问作者，这个有没有在生产上使用的案例

### ISSUE THREAD

**Issue by songjiesdnu** [makersoft/mybatis-shards#14]
看到作者的这个项目维护了也有三年的时间了，想问一下有没有在生产上使用的案例？
我们项目中准备采用这个方案。

**Comment by fengkuok** [comment]
我本人所在公司用的别的方案，所以很遗憾，我自己没在项目中用过这个。
后续我会补文档以及做推广的。

另外，你有什么好的建议可以邮件联系我。

**Comment by songjiesdnu** [comment]
你们用的是什么方案呢？是在哪个层次做的数据库的切分？

**Comment by fengkuok** [comment]
类似的方案，我自认为远远没有我这个好用！😄

**Comment by songjiesdnu** [comment]
哈哈，自信！！
另外想问一下，这个框架有没有使用缓存？就是加入分布式缓存，进一步降低对后台数据库的压力？

**Comment by fengkuok** [comment]
缓存不属于这个框架的范畴。
MyBatis自身对缓存也做了支持的，你可以参考下：
mybatis-redis : http://mybatis.github.io/redis-cache/
mybatis-memcached : http://mybatis.github.io/redis-cache/

**Comment by songjiesdnu** [comment]
多谢作者
